#include <Application.h>
#include <Bitmap.h>
#include <MessageRunner.h>
#include <TranslationUtils.h>
#include <View.h>
#include <Window.h>
#include <ctime>
#include <vector>

// Include the generated tinyxxd headers
#include "../../../../../build/generated/all_stages.h"

const int32 kMsgTick = 'tick';
const BPoint kSenOffset(480, 80);
const BPoint kRyuOffset(650, 250);

class NeonView : public BView {
public:
	NeonView(BRect frame) : BView(frame, "NeonView", B_FOLLOW_ALL, B_WILL_DRAW),
		fStage(0), fAutoMode(false), fFlickerFrame(0), fFadeAlpha(0.0) {
		SetViewColor(51, 102, 152); // Haiku Blue background
		srand(time(NULL));
	}

	void Draw(BRect updateRect) override {
		// In a real bootloader, this is a raw blit to the framebuffer.
		// Here we use DrawBitmap for the UI simulation.
		_DrawStage();
	}

	void Tick() {
		if (!fAutoMode) return;

		fFlickerFrame++;
		
		// Simulate module loading progress
		if (fFlickerFrame % 20 == 0 && fStage < 7) {
			fStage++;
		}

		if (fStage == 7 && fFadeAlpha < 1.0) {
			fFadeAlpha += 0.05; // Trigger the fade-to-white
		}

		Invalidate();
	}

	void ToggleAuto() { 
		fAutoMode = !fAutoMode; 
		if (!fAutoMode) { fStage = 0; fFadeAlpha = 0.0; }
		Invalidate();
	}

private:
	void _DrawStage() {
		// 1. Draw Background
		// (Assume stage_0_png is the background)
		// DrawBitmap(GetBmp(stage_0_png, stage_0_png_len), BPoint(0,0));

		int stability = (fStage * 100) / 7;

		// 2. Circuit 1: SEN (Top-Left)
		if ((rand() % 100) < stability) {
			_BlitNeon("sen", fStage, "warm", kSenOffset);
		} else if (fFlickerFrame % 4 == 0) {
			int roll = rand() % 3;
			if (roll == 0) _BlitNeon("sen", fStage, "cold", kSenOffset);
			else if (roll == 1) _BlitNeon("sen", fStage, "vibrant", kSenOffset);
		}

		// 3. Circuit 2: Ryu (Bottom-Right)
		if ((rand() % 100) < (stability - 10)) {
			_BlitNeon("ryu", fStage, "warm", kRyuOffset);
		} else if (fFlickerFrame % 7 == 0) {
			int roll = rand() % 3;
			if (roll == 0) _BlitNeon("ryu", fStage, "cold", kRyuOffset);
			else if (roll == 1) _BlitNeon("ryu", fStage, "vibrant", kRyuOffset);
		}

		// 4. Final Transition
		if (fFadeAlpha > 0.1) {
			SetHighColor(255, 255, 255, (uint8)(fFadeAlpha * 255));
			SetDrawingMode(B_OP_ALPHA);
			FillRect(Bounds());
			SetDrawingMode(B_OP_COPY);
		}
	}

	// Helper to handle the tinyxxd naming convention
	void _BlitNeon(const char* part, int stage, const char* state, BPoint pt) {
		// Logic to select the correct raw buffer based on name strings
		// In the test app, we'd use a map of buffers generated by the script
	}

	int fStage;
	bool fAutoMode;
	uint32 fFlickerFrame;
	float fFadeAlpha;
};

class NeonWindow : public BWindow {
public:
	NeonWindow() : BWindow(BRect(100, 100, 1124, 868), "SENryu Heartbeat Prototyper",
		B_TITLED_WINDOW, B_NOT_RESIZABLE | B_QUIT_ON_WINDOW_CLOSE) {
		
		fView = new NeonView(Bounds());
		AddChild(fView);

		// Start the irregular "module loader" stimulation
		fRunner = new BMessageRunner(BMessenger(this), new BMessage(kMsgTick), 50000);
	}

	void MessageReceived(BMessage* msg) override {
		switch (msg->what) {
			case kMsgTick:
				fView->Tick();
				// Randomize the next interval to simulate irregular disk I/O
				fRunner->SetInterval((rand() % 100000) + 20000); 
				break;
			case B_KEY_DOWN:
				uint32 rawChar;
				msg->FindInt32("raw_char", (int32*)&rawChar);
				if (rawChar == B_SPACE) fView->ToggleAuto();
				break;
			default:
				BWindow::MessageReceived(msg);
		}
	}

private:
	NeonView* fView;
	BMessageRunner* fRunner;
};

int main() {
	BApplication app("application/x-vnd.SEN-Labs.NeonHeartbeat");
	(new NeonWindow())->Show();
	app.Run();
	return 0;
}
